# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ee6d30a78b59e3f9aa172b27537858f585c8e733bb8b2cf533f76439ffea5dff4d28b732dff310b22f926ffa263e515d113e1e20c6ea1eee0c6c25337a32f12d

test:
  secret_key_base: e92c9acb3fd32479742c26b9275b2d43e8ac64365574d9c2aeab757d703dbecd3282c9568362a2f5661112948d14eea18d62661c85a0321862cb0ec51cf46a87

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
